### ISSUE TITLE
Error in sample file

### ISSUE THREAD

**Issue by Rasbats** [AndyNibbs/RTZ#16]
Validating the file 'RTZ1.1AllOptionalElementsAndAttributes' with Xerces gave me several validation errors:

VALIDATION ERRORS FOUND:
file:///C:\Projects\ECDIS\rtz-sax\build\Debug\RTZ1.1AllOptionalElementsAndAttributes.rtz:98:68
minutes value '2020-02-18T00:00:00z' must be between 0 and 59file:///C:\Projects\ECDIS\rtz-sax\build\Debug\RTZ1.1AllOptionalElementsAndAttributes.rtz:103:168
minutes value '2020-02-27T21:38:42z' must be between 0 and 59file:///C:\Projects\ECDIS\rtz-sax\build\Debug\RTZ1.1AllOptionalElementsAndAttributes.rtz:103:168
minutes value '2020-02-27T23:38:42z' must be between 0 and 59file:///C:\Projects\ECDIS\rtz-sax\build\Debug\RTZ1.1AllOptionalElementsAndAttributes.rtz:106:65
minutes value '2020-02-18T00:00:00z' must be between 0 and 59file:///C:\Projects\ECDIS\rtz-sax\build\Debug\RTZ1.1AllOptionalElementsAndAttributes.rtz:107:65
minutes value '2020-02-18T00:04:22z' must be between 0 and 59file:///C:\Projects\ECDIS\rtz-sax\build\Debug\RTZ1.1AllOptionalElementsAndAttributes.rtz:108:65
minutes value '2020-02-25T17:36:25z' must be between 0 and 59file:///C:\Projects\ECDIS\rtz-sax\build\Debug\RTZ1.1AllOptionalElementsAndAttributes.rtz:109:65
minutes value '2020-02-27T14:17:34z' must be between 0 and 59file:///C:\Projects\ECDIS\rtz-sax\build\Debug\RTZ1.1AllOptionalElementsAndAttributes.rtz:110:65
minutes value '2020-02-27T19:26:51z' must be between 0 and 59file:///C:\Projects\ECDIS\rtz-sax\build\Debug\RTZ1.1AllOptionalElementsAndAttributes.rtz:111:65
minutes value '2020-02-27T21:38:42z' must be between 0 and 59file:///C:\Projects\ECDIS\rtz-sax\build\Debug\RTZ1.1AllOptionalElementsAndAttributes.rtz:120:144
minutes value '2020-02-18T00:00:00z' must be between 0 and 59file:///C:\Projects\ECDIS\rtz-sax\build\Debug\RTZ1.1AllOptionalElementsAndAttributes.rtz:121:375
minutes value '2020-02-18T00:04:22z' must be between 0 and 59file:///C:\Projects\ECDIS\rtz-sax\build\Debug\RTZ1.1AllOptionalElementsAndAttributes.rtz:122:390
minutes value '2020-02-25T17:36:25z' must be between 0 and 59file:///C:\Projects\ECDIS\rtz-sax\build\Debug\RTZ1.1AllOptionalElementsAndAttributes.rtz:123:95
minutes value '2020-02-27T14:17:34z' must be between 0 and 59file:///C:\Projects\ECDIS\rtz-sax\build\Debug\RTZ1.1AllOptionalElementsAndAttributes.rtz:124:95
minutes value '2020-02-27T19:26:51z' must be between 0 and 59file:///C:\Projects\ECDIS\rtz-sax\build\Debug\RTZ1.1AllOptionalElementsAndAttributes.rtz:125:95
minutes value '2020-02-27T21:38:42z' must be between 0 and 59

The error is caused by using 'z' and not 'Z' in the time string.

**Comment by AndyNibbs** [comment]
Thanks. This is fixed now. Closing this off.
